#ifndef __AnimationGeneratorMainFrame__
#define __AnimationGeneratorMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "animation-generator-gui.h"

//// end generated include
#include <vector>
#include <string>
#include <wx/filedlg.h>

class AnimationGeneratorUI;
class AnimationGeneratorUIActions;
class AnimationGeneratorMainFrame;

#include "animation-generator-ui.h"
#include "animation-generator-ui-actions.h"

/** Implementing MainFrame */
class AnimationGeneratorMainFrame : public MainFrame
{
	wxImage startFrame;
	wxImage endFrame;

protected:
	// Handlers for MainFrame events.
	void onLoadInitFrame(wxCommandEvent& event);
	void onLoadLastFrame(wxCommandEvent& event);
	void onReset(wxCommandEvent& event);
	void onTransitionChoice(wxCommandEvent& event);
	void onFrameRateEnter(wxSpinEvent& event);
	void onGenerateFrame(wxCommandEvent& event);
	void onScroll(wxScrollEvent& event);
	void onAnimationSave(wxCommandEvent& event);
public:
	/** Constructor */
	AnimationGeneratorMainFrame(wxWindow* parent);
	//// end generated class members
	AnimationGeneratorMainFrame(wxWindow*, std::vector<std::wstring>, AnimationGeneratorUIActions&);
	AnimationGeneratorUI* getUI();
private:
	AnimationGeneratorUI* animationGeneratorUI;
	AnimationGeneratorUIActions* actions;
	void setPolishLabels();
};

#endif // __AnimationGeneratorMainFrame__
