#ifndef __animation-generator-main-frame__
#define __animation-generator-main-frame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "animation-generator-gui.h"

//// end generated include

/** Implementing MainFrame */
class AnimationGeneratorMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void onReset( wxCommandEvent& event );
		void onLoadInitFrame( wxCommandEvent& event );
		void onLoadLastFrame( wxCommandEvent& event );
		void onTransitionChoice( wxCommandEvent& event );
		void onFrameRateEnter( wxCommandEvent& event );
		void onGenerateFrame( wxCommandEvent& event );
		void onScroll( wxScrollEvent& event );
		void onAnimationSave( wxCommandEvent& event );
	public:
		/** Constructor */
		AnimationGeneratorMainFrame( wxWindow* parent );
	//// end generated class members

};

#endif // __animation-generator-main-frame__
